### ISSUE TITLE
miss return after notify call back and send one more time request after timeout

### ISSUE THREAD

**Issue by leolin0102** [shaioz/AFNetworking-AutoRetry#22]
if (!retriesRemainingCount) {
            ARLog(@"AutoRetry: Request failed %d times: %@", originalRetryCount, error.localizedDescription);
            ARLog(@"AutoRetry: No more retries allowed! executing supplied failure block...");
            failure(task, error);
            ARLog(@"AutoRetry: done.");
           //There should add a return; ?
        }

**Comment by leolin0102** [comment]
AFHTTPSessionManager+AutoRetry

**Comment by jold** [comment]
thank you, done!

**Comment by leolin0102** [comment]
And one more things, set timeout seem doesn’t work for HTTP POST,  set requestSerializer.timeoutInterval can control the timeout.在 2017年1月4日，下午7:07，Daniel Jankovič <notifications@github.com> 写道：Closed #22.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shaioz/AFNetworking-AutoRetry","title":"shaioz/AFNetworking-AutoRetry","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/shaioz/AFNetworking-AutoRetry" class="">https://github.com/shaioz/AFNetworking-AutoRetry</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #22."}],"action":{"name":"View Issue","url":"<a href="https://github.com/shaioz/AFNetworking-AutoRetry/issues/22#event-911035022" class="">https://github.com/shaioz/AFNetworking-AutoRetry/issues/22#event-911035022</a>"}}}
