### ISSUE TITLE
Doesn't build with `use_frameworks!` in Podfile

### ISSUE THREAD

**Issue by wgrand** [shaioz/AFNetworking-AutoRetry#23]
If `use_frameworks!` is specified in the Podfile, the import statement isn't in the right format to work with a framework: https://github.com/shaioz/AFNetworking-AutoRetry/blob/master/AFHTTPSessionManager%2BAutoRetry.m#L5

and I get an build error that says, `Pods/AFNetworking+AutoRetry/AFHTTPSessionManager+AutoRetry.m:5:9: 'AFNetworking+AutoRetry/AFHTTPRequestOperationManager+AutoRetry.h' file not found`

<img width="610" alt="screen shot 2016-12-29 at 4 01 59 pm" src="https://cloud.githubusercontent.com/assets/6401653/21554753/3f9f5544-cde0-11e6-9fc0-9d365c5fa55b.png">

**Comment by jold** [comment]
fixed
