### ISSUE TITLE
Do not retry on intentional errors

### ISSUE THREAD

**Issue by tasomaniac** [shaioz/AFNetworking-AutoRetry#4]
The library retries whenever an error occurs. But some errors will definitely occurs whenever you try. For example error 400, it mean the input parameters are wrong. For example, you are calling a "login" call with wrong username and password. There is no mean to retry this call. It will give 400 and doing it 3 times slows the app. 

I think the behaviour can be changed to this: Retry it if the status code is not like 2xx nor 4xx

**Comment by jold** [comment]
Library extension now does not auto-retry when common HTTP error or just warning code occur. e.g. Host Not Found, Bad URL or Http Redirect

**Comment by tasomaniac** [comment]
:+1:
